---
- hosts: app
  become: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.git
    - geerlingguy.nodejs
    - geerlingguy.ruby
    - geerlingguy.passenger

  tasks:
    - name: Install app dependencies for mysql.
      apt: "name={{ item }} state=present"
      with_items:
        - mysql-client
        - libmysqlclient-dev

#    - name: Install app dependencies for sqlite.
#      apt: "name={{ item }} state=present"
#      with_items:
#        - libsqlite3-dev
#        - libreadline-dev

    - name: Ensure app directory exists and is writeable.
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: 0755
