---
mysql_replication_user: {name: 'replication', password: 'secret'}
mysql_databases:
  - name: myticketee_production
    collation: utf8_general_ci
    encoding: utf8

# MySql general log
mysql_log: "/var/log/mysql/mysql-general.log"

# Slow query log settings.
mysql_slow_query_log_enabled: yes
mysql_slow_query_time: "2"